languageCode = "ja"
title = "オトナのプログラミング勉強会"
baseurl = "http://otona.pro/"
theme = "vienna"

[params]
	facebook = "オトナのプログラミング勉強会-1343421652358699"
	contact = "mailto:info@otona.pro"
	subtitle = "熊本のプログラミング勉強会の講座録"
	bio = "熊本で月2回開催されるオトナのプログラミングの勉強会"
	ga_api_key = "UA-106489461-1"
